### ISSUE TITLE
Windows 10 64 bit Reports App Not 64-bit compatible

### ISSUE THREAD

**Issue by gentlesartori** [naderi/nextcloud-client-portable#1]
I downloaded the latest application and tried to run it on my Windows 10 Pro x64 PC. I get an error message titled "Unsupported 16-bit Application" when I run NextCloud Portable.exe. Running NextCloud.exe from the App directory gives me "This app can't run on your PC"

**Comment by naderi** [comment]
Hi @gentlesartori ,
I can not regenerate the error on my side. I myself also have windows 10 64bit and can start the program without problems.
Please try to download and run the latest version from the [release page](https://github.com/naderi/nextcloud-client-portable/releases/latest).
