### ISSUE TITLE
"This app can't run on your PC" when trying to install

### ISSUE THREAD

**Issue by erdie721** [naderi/nextcloud-client-portable#3]
Trying to run this on Windows 10 Enterprise (Version 10.0.19045 Build 19045) and I get a "This app can't run on your PC" windows error when trying to install. I don't have any other information available.

**Comment by naderi** [comment]
@erdie721 Thanks for reporting.
I've now updated the client to the most recent version, and it works on my Windows 11.
Could you please try again?
